"""Back to string UUID conflict

Revision ID: 05d3534fd38a
Revises: fdf8ea1b3f2a
Create Date: 2026-02-22 11:25:35.503960

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05d3534fd38a'
down_revision = 'fdf8ea1b3f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meaning', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meaning', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
