languages_by_region = {
    "Europe": {
        "en": "English — English",
        "fr": "French — français",
        "es": "Spanish — español",
        "de": "German — Deutsch",
        "it": "Italian — italiano",
        "pt": "Portuguese — português",
        "nl": "Dutch — Nederlands",
        "sv": "Swedish — svenska",
        "da": "Danish — dansk",
        "fi": "Finnish — suomi",
        "pl": "Polish — polski",
        "cs": "Czech — čeština",
        "el": "Greek — Ελληνικά",
        "ro": "Romanian — română",
        "hu": "Hungarian — magyar",
        "uk": "Ukrainian — українська",
        "ru": "Russian — русский",
        "tr": "Turkish — Türkçe",
        "sr": "Serbian — српски",
        "hr": "Croatian — hrvatski",
        "bs": "Bosnian — bosanski",
        "sk": "Slovak — slovenčina",
        "sl": "Slovenian — slovenščina",
        "bg": "Bulgarian — български",
        "lt": "Lithuanian — lietuvių",
        "lv": "Latvian — latviešu",
        "et": "Estonian — eesti",
        "ga": "Irish — Gaeilge",
        "cy": "Welsh — Cymraeg",
        "is": "Icelandic — íslenska",
        "mt": "Maltese — Malti",
    },
    "Asia": {
        "ja": "Japanese — 日本語",
        "ko": "Korean — 한국어",
        "zh-CN": "Chinese (Simplified) — 简体中文",
        "zh-TW": "Chinese (Traditional) — 繁體中文",
        "hi": "Hindi — हिन्दी",
        "bn": "Bengali — বাংলা",
        "ur": "Urdu — اردو",
        "th": "Thai — ไทย",
        "vi": "Vietnamese — Tiếng Việt",
        "tl": "Tagalog — Wikang Tagalog",
        "ceb": "Visaya (Cebuano) — Binisaya",
        "id": "Indonesian — Bahasa Indonesia",
        "ms": "Malay — Bahasa Melayu",
        "ta": "Tamil — தமிழ்",
        "te": "Telugu — తెలుగు",
        "ml": "Malayalam — മലയാളം",
        "mr": "Marathi — मराठी",
        "kn": "Kannada — ಕನ್ನಡ",
        "pa": "Punjabi — ਪੰਜਾਬੀ",
        "gu": "Gujarati — ગુજરાતી",
        "ne": "Nepali — नेपाली",
        "si": "Sinhala — සිංහල",
        "my": "Burmese — မြန်မာစာ",
        "km": "Khmer — ខ្មែរ",
        "lo": "Lao — ລາວ",
        "mn": "Mongolian — Монгол",
    },
    "Africa": {
        "sw": "Swahili — Kiswahili",
        "am": "Amharic — አማርኛ",
        "yo": "Yoruba — Yorùbá",
        "ig": "Igbo — Igbo",
        "zu": "Zulu — isiZulu",
        "xh": "Xhosa — isiXhosa",
        "af": "Afrikaans — Afrikaans",
        "ha": "Hausa — Hausa",
        "st": "Sesotho — Sesotho",
        "ts": "Tsonga — Xitsonga",
        "rw": "Kinyarwanda — Ikinyarwanda",
        "so": "Somali — Soomaali",
        "tn": "Setswana — Setswana",
        "ln": "Lingala — Lingála",
        "mg": "Malagasy — Malagasy",
        "ti": "Tigrinya — ትግርኛ",
    },
    "Americas": {
        "en": "English — English",
        "es": "Spanish — español",
        "pt": "Portuguese — português",
        "fr": "French — français",
        "ht": "Haitian Creole — Kreyòl Ayisyen",
        "qu": "Quechua — Runa Simi",
        "gn": "Guarani — Avañe'ẽ",
        "ay": "Aymara — Aymar aru",
        "cr": "Cree — Nēhiyawēwin",
        "mo": "Mohawk — Kanien’kéha",
        "na": "Nahuatl — Nāhuatl",
        "map": "Mapudungun — Mapudungun",
    },
    "Middle East": {
        "ar": "Arabic — العربية",
        "he": "Hebrew — עברית",
        "fa": "Persian (Farsi) — فارسی",
        "ku": "Kurdish — Kurdî",
        "ps": "Pashto — پښتو",
        "tr": "Turkish — Türkçe",
        "ckb": "Kurdish (Sorani) — کوردی",
        "syc": "Syriac — ܠܫܢܐ ܣܘܪܝܝܐ",
        "dv": "Dhivehi (Maldivian) — ދިވެހި",
    },
    "Oceania": {
        "en": "English — English",
        "mi": "Māori — te reo Māori",
        "sm": "Samoan — Gagana Sāmoa",
        "to": "Tongan — lea faka-Tonga",
        "fj": "Fijian — Vosa Vakaviti",
        "haw": "Hawaiian — ʻŌlelo Hawaiʻi",
        "pap": "Tok Pisin — Tok Pisin",
    },
}
